### PR TITLE
Set content height of uncollapsed components upon initial mounting

### PR DESCRIPTION
**Pull request by aarontrank**

### CODE REVIEW

**Comment by rohozhnikoff** [comment]
same problem, tnx for solution

small jump still exist ( will look later how to fix it

**Comment by iRoachie** [comment]
@aarontrank Can you rebase with `next` branch ?

**Comment by aarontrank** [comment]
@iRoachie done :)

**Comment by iRoachie** [comment]
Will do some testing first.

**Comment by iRoachie** [comment]
Not sure if this PR is needed anymore since we have the `initiallyActiveSection` prop from the issue linked above. Let me know the use case for a change like this.

**Pull request closed without merging**
