### PR TITLE
Migrate to use reanimated

### PR DESCRIPTION
**Pull request by oblador**
**Pro**: Allows us to use native driver for smoother animations.
**Con**: Breaking change that adds a new dependency, however the majority of RN installations already have it.

### CODE REVIEW

**Comment by HashibulAmin** [comment]
+1

**Review by akinncar — APPROVED** [review]

**Comment by oblador** [comment]
@HashibulAmin & @akinncar Have you tried this PR out? Would love to get some feedback from real world use cases.

**Comment by akinncar** [comment]
I just tried this feature with the Example app, and create a repo to test it https://github.com/akinncar/expo-collapsible-example

`"react-native-collapsible": "git://github.com/oblador/react-native-collapsible.git#reanimated"` on `package.json`

### iOS Device


### Android Emulator


Let me know if I can help with anything more, I don't have other examples yet.

**Comment by oblador** [comment]
@akinncar Thanks! I've tried those as well, would be great to have some real world tryouts too 👍

**Comment by ibealec** [comment]
Nice improvement! I tried this in my project and the animation is noticeably smoother. Not sure how others would feel about the "Pure JavaScript" part going away, but as someone who just needs this on mobile and already has reanimated installed, it was a welcome change.

**Comment by mwegener-com** [comment]
Working fine in my project. 
Bug with nested collapsibles still exists.

**Comment by fobos531** [comment]
Hey @oblador, is a new version which includes this change going to be published to NPM?

**Comment by wmonecke** [comment]
@oblador Could you help me understand why this PR was reverted? I really enjoy using this package but with 120Hz displays the current JS implementation has started to fall behind my other Reanimated components.

Would you be willing to merge a PR with the reanimated v2 API? I would gladly submit one.

**Pull request merged**
