### PR TITLE
Add Sections parameter to the renderHeader and renderContent callbacks.

### PR DESCRIPTION
**Pull request by peacechen**
See #126

### CODE REVIEW

**Comment by iRoachie** [comment]
Can you create a scenario where this would be used? Not sure I understand the purpose

**Comment by peacechen** [comment]
1) A master list is fetched from a server.
2) The master list is filtered by name and sorted by date based on user selection.
3) The resulting sections are fed to <Accordion> dynamically.
4) The contents of the Accordion subsequently need to access the entire sections object for data such as total customers, costs, etc.

Without this PR, each content in each Accordion section only has access to its own slice of data (the section).  In my case each section needs visibility to the entire _sections_ array.

**Comment by iRoachie** [comment]
Hey @peacechen, I'd love tho see this in action, can you create an example repo with this behavior with an example?

**Comment by peacechen** [comment]
For our app, I ended up leveraging `isActive` to simplify the code so I don't have a good example at the moment.
In complex use cases, I still believe that having access to the full `sections` array would be beneficial.  There's virtually no cost to passing an extra parameter reference.

**Comment by iRoachie** [comment]
Alright then!

**Pull request merged**
