### PR TITLE
Adding prop to force activeSection

### PR DESCRIPTION
**Pull request by pkruzlics**
Adding prop to be able to specify the activeSection externally. This is useful when the item inside the Accordion (e.g. a "Next" button)can trigger the following item to auto-expand.

### CODE REVIEW

**Comment by pkruzlics** [comment]
I'd like to propose this as a new feature to be able to manually select which section in the Accordion gets expanded. My use case is we use the Accordion to display Yes/No questions, and I would like to have the next section auto-expand when the user selects an answer. Please let me know if you need any additional info, thanks!

**Comment by oblador** [comment]
Thanks for your PR! Would like to support this usecase too: https://github.com/oblador/react-native-collapsible/issues/29

I'd like to propose a slightly different approach: 
* `undefined` = ignore the prop, meaning it's uncontrolled
* `false` = no active section

Also if `activeSection` is not `undefined` the state itself shouldn't change, only `onChange` should be called. 

Adding this to README would be appreciated too 👍

**Comment by pkruzlics** [comment]
You're very welcome :) It's a great project, and it's been very useful in my projects!

I purposely left the state in there so that the Accordion can still control/know its own state (e.g. user clicks a 'Next Section' button, but then also manually clicks on one of the sections to expand). I did add the ability to close all sections by passing in 'false'.

I've also updated the README as well as the Accordion example, please let me know if it all looks ok!

**Comment by oblador** [comment]
@pkruzlics: I'd have to disagree there. You can still do that by setting state with `onChange` otherwise it's inconsistent. This is how react native core modules work too, like `SwitchIOS`.

**Comment by pkruzlics** [comment]
@oblador The situation I have is that I can expand the Accordion sections but clicking on the headers OR clicking on a button inside the sections. The issue that I'm having is that if I don't set the state in the '_toggleSection' function, if I expanded a section by button click, the header-clicks no longer open up any of the sections.

I've pushed the onChange check you mentioned, would you be able to take a look at the example app and let me know if there is a better way of implementing it? Thanks for your help!

**Comment by oblador** [comment]
@pkruzlics: If your "owner component" claims control over that state, there should only be one source of truth. That means you should change the state in the owner when `onChange` is called and pass it down as a prop. Hope that makes sense.

**Comment by pkruzlics** [comment]
@oblador Ahhh yes, it does make sense. Apologies, the example I was using to test the functionality didn't properly handle the onchange event, but I do have it now working properly...

Please let me know if there's anything else that needs to be done before it can get merged in. Thanks for your help!

**Comment by oblador** [comment]
Sorry it took so long to merge, forgot about it. Thanks for your contribution!

**Comment by pkruzlics** [comment]
Awesome thanks! Glad I could help out!

**Pull request merged**
