### PR TITLE
Add style prop to create cards/containers

### PR DESCRIPTION
**Pull request by M-Jas**
## What does this PR do?
- Gives users the ability to add styling to the entire accordion container. We needed to create cards for each header item in the accordion that were seamlessly connected to header. Please see the image below.

## Anything Else We Should Know?
- Your PR process requests that we push to the ```next``` branch, but I only see master. 

## Images
simulator screen shot - iphone x - 2018-10-03 at 10 07 25

### CODE REVIEW

**Comment by iRoachie** [comment]
Man that is a beautiful app 💯, seems like a duplicate of #246 . However if you can finish the changes before, then i'll merge yours.

Still need to add typescript definitions and fix the ci

**Comment by M-Jas** [comment]
@iRoachie Sorry I added the wrong picture, but the new one is up with the Accordion in full force. I'll take a look into #246 and Mr. Travis.

**Comment by M-Jas** [comment]
@iRoachie how do you run the ci locally? I don't have this '.' it speaks of.

**Comment by iRoachie** [comment]
You can run `npm run test --fix` and see if that works

**Comment by M-Jas** [comment]
@iRoachie helps if you ```npm i``` 😞. I think this last push should do the trick.

**Comment by iRoachie** [comment]
Lastly can you add it to defaultProps https://github.com/oblador/react-native-collapsible/blob/b21aa79e565f0478c243d0ec347df39bc48a55d9/Accordion.js#L31

**Comment by iRoachie** [comment]
Oops forgot the docs! Add it to the readme

**Comment by M-Jas** [comment]
Ok this time for real! Sorry for the back and forth.

**Comment by iRoachie** [comment]
Thanks mate! Release will be out soon

**Pull request merged**
