### PR TITLE
Update Collapsible.js with useNativeDriver which allows parallel process

### PR DESCRIPTION
**Pull request by zoiec**
This PR continues with the changes made in https://github.com/oblador/react-native-collapsible/pull/235 with merge conflicts resolved. 

With this change, animations can run parallel to other processes taking place such as AWS AppSync queries or mutations

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @zoiec as per my last comment in the previous issue i wanted to know if they were any measurable performance improvements/observations over the current implmentation

**Comment by prscX** [comment]
Hi: Can someone please look into this PR. I hope it will boost animation performance.

Thanks
</ Pranav >

**Comment by bneigher** [comment]
@iRoachie - while it's true that having benchmarks on the performance improvements is nice, in this case I think it should suffice to merge this as it is a fact that not sending the animation across the bridge leads to poorer performance.  Even if a measurable speedup is marginal, the parallel nature of how sending animations to the native engine is a strong enough case to accept this as an update.

I'm using this fork over the official because of it, but would like to keep using this official module.

Cheers

**Comment by zaptrem** [comment]
Interested in this change. Anything keeping it from being merged?

**Comment by sourcecode911** [comment]
+1

**Comment by oblador** [comment]
Hi, the `useNativeDriver` option was not provided to the right animation so in essence it doesn't change anything. Unfortunately it doesn't work on layout properties such as `height`, so if you pass it to the right place it crashes. Using something like `react-native-animated` would work though. Closing this for now.

**Pull request closed without merging**
