### PR TITLE
Make it work with new RN version

### PR DESCRIPTION
**Pull request by ms88privat**
see also https://github.com/facebook/react-native/issues/11439 and https://github.com/oblador/react-native-collapsible/pull/67

### CODE REVIEW

**Comment by CapitanRedBeard** [comment]
It looks like we have a general upgrade solution (#67) and a cleaner solution for the scrollView (this). So we should meet in the middle and merge something soon.  0.41 is almost out and I'm managing a fork of this repo right now as a solution but that is not ideal and would love to move off of that.

**Comment by oblador** [comment]
Thank you for your efforts, but fortunately this bug is fixed in react-native master and this component will start working again (hopefully) with the next release. If you want you can build your project directly from master.

**Comment by CapitanRedBeard** [comment]
So just to clarify, this bug exists in RN0.40, but will be resolved around RN0.42? I'm working on a project where I need to point to a stable version, so I can stay at 0.39 instead of pointing to master, I just don't want to fall behind on upgrades because they can get tricky quickly. Thanks for the quick reply @oblador

**Comment by oblador** [comment]
0.42 at the latest yes, if we're lucky 0.41 stable.

**Comment by CapitanRedBeard** [comment]
Thanks man!

**Pull request closed without merging**
