### PR TITLE
Improved type definition for Accordion.d.ts

### PR DESCRIPTION
**Pull request by guptaamol**
There could be some work done for touchableProps as well.

### CODE REVIEW

**Comment by guptaamol** [comment]
Beautiful Library btw. Thanks a ton.

**Comment by iRoachie** [comment]
Nice! I mean to do this a while back

**Comment by guptaamol** [comment]
i would be happy to help in case you need anything else to be done on the
typescript end.

**Comment by iRoachie** [comment]
That's it for now i think, thanks again 💯

**Pull request merged**
