### PR TITLE
Remove typings

### PR DESCRIPTION
**Pull request by iRoachie**
@oblador You can remove the typings from here. I added them on DefinitelyTyped so you don't have to maintain them. Also updated them to include the Accordion as well.

### CODE REVIEW

**Comment by oblador** [comment]
Thanks! You've contributed a few good PRs lately, care to become co-maintainer?

**Comment by iRoachie** [comment]
Sure! I don't mind helping out where I can

**Comment by oblador** [comment]
👍  added you 😸

**Comment by iRoachie** [comment]
Nice! Anything I should know?

**Comment by oblador** [comment]
I prefer squashed commits and is cautious about unnecessarily breaking backwards compatibility 😄

**Comment by iRoachie** [comment]
Sounds good to me!

**Pull request merged**
