### PR TITLE
fix: measure content height on layout change

### PR DESCRIPTION
**Pull request by eduardomoroni**
When you were with collapsible opened (`state.collapsed = false`) and children changes it's height, Collapsible component was breaking the layout.

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey I think your PR looks good, can you just create a small example repo so I could see this in action? A before and after?

**Comment by eduardomoroni** [comment]
Hey @iRoachie, could I sent you a GIF? Reproduce this error might take a while and I don't have too much time lately :/

**Comment by iRoachie** [comment]
Sure that works, just make sure in the gif you can see both:
* the problem (before your PR)
* the solution (after your PR)

**Comment by ayushinigam** [comment]
Hi @iRoachie, 
I can confirm that the PR works. It fixes the issue of re measuring the height on layout change. 
It would be really helpful if you could merge it.

Thanks

**Comment by eduardomoroni** [comment]
Sorry guys, didn't have cycles to create a GIF or an example showing this working, could help us with that @ayushinigam?

**Comment by iRoachie** [comment]
@ayushinigam I would love to merge this PR if it fixes a problem. I just need to be sure **what it's supposed to fix**, and if it accurately does that. This is the reasoning behind asking for an example app maybe to be made so that the changes can be observed

**Comment by oliverdolgener** [comment]
@iRoachie why was this feature removed? I have the same problem: I am using the `Collapsible` with a `FlatList` as child that gets updated dynamically while the `collapsible` is not collapsed resulting in a wrong height calculation. The added items are shown only when collapsing and reopening the list.

**Comment by iRoachie** [comment]
@oliverdolgener because of https://github.com/oblador/react-native-collapsible/issues/168

**Comment by oliverdolgener** [comment]
@iRoachie oh that's too bad! But I understand the problems this caused. Do you have an idea for my problem? Is there a function I could call upon receiving new data to update the collapsible height?

**Comment by oliverdolgener** [comment]
@iRoachie I solved the problem by replacing my `FlatList` with a simple `map()` function. Not the most beautiful solution but it works!

**Comment by papigers** [comment]
For those who still have this problem, I've found a little hack that should be better than replacing `FlatList` with `map()` (especially for long lists). 
Set the initial value for collapsed to be `false`, and use `componentDidMount`/`useEffect`/`useFocusEffect` (=`react-navigation`) to set the collapsed value to be true on mount or screen focus.
The only downside (which I don't really consider as a downside but still) is that the user sees the initial uncollapse animation.

**Comment by wmonecke** [comment]
This PR introduces flickering. Anyone else experiencing the same?

**Comment by iatomic1** [comment]
> This PR introduces flickering. Anyone else experiencing the same?

Just using this library and i am experiencing the flickering 😂

**Pull request merged**
