### PR TITLE
v0.10.0

### PR DESCRIPTION
**Pull request by iRoachie**

### CODE REVIEW

**Comment by iRoachie** [comment]
Release prepared @oblador, release notes are [here](https://github.com/oblador/react-native-collapsible/releases/tag/0.10.0). Already bump package version, just to publish to npm.

You can also add me one of the code owners, so I won't have to bug you with publishing to npm. https://docs.npmjs.com/cli/owner. My user is iroachie on npm.

**Comment by oblador** [comment]
@iRoachie Thanks, I'll actually make this part of the CI so you only have to tag the thing!

**Comment by oblador** [comment]
Check the PR, did this way back in July but don't get why I never merged it to master :-)

**Comment by oblador** [comment]
Btw what's your npm username?

**Comment by iRoachie** [comment]
iroachie

**Comment by oblador** [comment]
Cool, added as owner now, but would still prefer only to release via CI.

**Comment by iRoachie** [comment]
I'm all for automation, didn't think it was that easy actually :D

**Comment by oblador** [comment]
Cool, can you re-tag the release and see if that'll trigger it?

**Comment by iRoachie** [comment]
Done

**Comment by oblador** [comment]
Think it didn't work because the commit you tagged still used the old config. Lemme try with latest.

**Comment by oblador** [comment]
Seems to have been picked up now: https://travis-ci.org/oblador/react-native-collapsible/builds/326494236

**Comment by oblador** [comment]
Boom

skarmavbild 2018-01-08 kl 19 34 49

**Comment by iRoachie** [comment]
Nice! Thank you! Learned a thing or two about travis

**Comment by oblador** [comment]
👌 Thank you man! Doing a heck of a job 🥇 💯

**Pull request merged**
