### PR TITLE
Fix React 16.3 deprecation warnings for componentWillReceiveProps.

### PR DESCRIPTION
**Pull request by peacechen**
See #162

### CODE REVIEW

**Comment by wrod7** [comment]
👀

**Comment by iRoachie** [comment]
Crashes the example app. Will look into a better fix.

**Comment by sijad** [comment]
also I don't like idea of using `setState()` in `componentDidUpdate()`

**Comment by iRoachie** [comment]
Yea me neither. Will see if I can rewrite the collapsible component in a better way

**Comment by peacechen** [comment]
What's the error?  I'll give the demo a run tomorrow.

Does React discourage using setState in componentDidUpdate?  I haven't seen an issue doing so.

**Comment by iRoachie** [comment]
The error is from the component updating too much Times. Probably with the setState in componentDidUpdate. Infinite loop basically

**Comment by peacechen** [comment]
You're right, it can infinite loop since it's not checking the previous value of `activeSection`.

I pushed the fix for that in PR #214 (not sure why it's not showing up in this PR).  Please give it a go.  I couldn't manage to run the example due to cascading errors.  First error encountered was

> Unable to resolve ../../../../App" from ".//node_modules/react-native-scripts/build/bin/crna-entry.js`: The module `../../../../App` could not be found"

because the file `Example/app.js` is lowercase.  Surprised this hasn't been seen before. Are you all developing on Windows?

Next error it's unable to resolve module NavigatorIOS from react-native.  Cleared watchman, node_modules, etc but couldn't get past that.

**Comment by sijad** [comment]
maybe we should use `UNSAFE_` for now. I don't like neither `getDerivedStateFromProps` nor `componentDidUpdate` with current implementation.

@peacechen please try `yarn start --reset-cache`

**Comment by sijad** [comment]
sorry `UNSAFE_` does not fix this issue.

**Comment by peacechen** [comment]
`componentDidUpdate` isn't all that much different from `componentWillReceiveProps`

Did #214 fix the infinite loop?  It's a straight-forward and common fix for evaluating props.

**Comment by CiscoMossi** [comment]
Any update?

**Pull request merged**
